name: CI

on:
  workflow_dispatch:

  push:
    branches: [ master, main, feature-soc-v3 ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on:
  workflow_dispatch:
 ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version:
  workflow_dispatch:
 '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Angular App
      run: npx ng build --configuration production
      env:
        NODE_OPTIONS: --max_old_space_size=4096

